// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNG-LdWamfE4zajoiMhvhiA-BTC2lc-K8',
    appId: '1:185022920067:web:d59c0c893abce5ea35f2b6',
    messagingSenderId: '185022920067',
    projectId: 'fir-app-1183c',
    authDomain: 'fir-app-1183c.firebaseapp.com',
    storageBucket: 'fir-app-1183c.firebasestorage.app',
    measurementId: 'G-DP221XKVSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9JBAFFhhDPH44pTDZZNGVhjYKZB6BjYQ',
    appId: '1:185022920067:android:aaa71b751ec1469735f2b6',
    messagingSenderId: '185022920067',
    projectId: 'fir-app-1183c',
    storageBucket: 'fir-app-1183c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF2yEmGDb_0tnA9SDapNTqxWd2mocjXnA',
    appId: '1:185022920067:ios:d2a24068ad34008535f2b6',
    messagingSenderId: '185022920067',
    projectId: 'fir-app-1183c',
    storageBucket: 'fir-app-1183c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF2yEmGDb_0tnA9SDapNTqxWd2mocjXnA',
    appId: '1:185022920067:ios:d2a24068ad34008535f2b6',
    messagingSenderId: '185022920067',
    projectId: 'fir-app-1183c',
    storageBucket: 'fir-app-1183c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNG-LdWamfE4zajoiMhvhiA-BTC2lc-K8',
    appId: '1:185022920067:web:7aeac02832cd6b2035f2b6',
    messagingSenderId: '185022920067',
    projectId: 'fir-app-1183c',
    authDomain: 'fir-app-1183c.firebaseapp.com',
    storageBucket: 'fir-app-1183c.firebasestorage.app',
    measurementId: 'G-7WEPMWNGM3',
  );
}
